export default {
    minified: {
        //General vocabulary
        'nick': 'nickname',
        'enemyCount': '༜',
            //Color vocabulary
            'color1': '▶ A #',
            'color2': '▶ B #',
            'color3': '◆ #',
            'color4': '⬤ #',
            'color5': '⦾ #',
            'color6': '○ #',
            'color7': '◙ #',
            'color8': '⦿ #',
            'color9': '◌ #',
        'title': 'title',
        'artist': 'artist',
        'difficulty': '✪',
        'designer': '🕺',
        'MP3name': '♫',
        'bgBlack_true': 'bg is black',
        'bgBlack_false': 'bg is not black',
        'audioPreview': '⏳',
        'subtitle': 'sub',

        //Marker vocabulary
        'time': '@',
        'enemies': 'o>',
        'warpType': 'this is a',
            'timeWarp': 'timeWarp marker',
            'spinRate': 'spinRate marker',
        'val': 'his value is',
        'shotType': 'shoots',
            'bulletType': 'of',
        'aim': 'aimed at the',
            'mid': 'middle',
            'pl': 'player',
        'offset0': '-offset',
        'offset1': '+offset',
        'amount0': '-amount',
        'amount1': '+amount',
        'angle0': '-angle',
        'angle1': '+angle',
        'speed0': '-speed',
        'speed1': '+speed',
        'rows': 'row count is',
        'lifespan': 'tracking time is',
        'duration': 'duration is'
    },
    en: {
        //General vocabulary
        'nick': 'the nickname is',
        'enemyCount': 'the ennemy count is',
            //Color vocabulary
            'color1': 'the linear A color is #',
            'color2': 'the linear B color is #',
            'color3': 'the homing color is #',
            'color4': 'the bubble color is #',
            'color5': 'the outline color is #',
            'color6': 'the outer rings color is #',
            'color7': 'the slow-motion color is #',
            'color8': 'the score circle color is #',
            'color9': 'the hug color is #',
        'title': 'the title of the level is',
        'artist': 'the song is made by',
        'difficulty': 'the difficulty is',
        'designer': 'the creator is',
        'MP3name': 'the mp3 file used is',
        'bgBlack_true': 'the background is black',
        'bgBlack_false': 'the background is not black',
        'audioPreview': 'the audio preview starts at',
        'subtitle': 'the subtitle for this level is',

        //Marker vocabulary
        'time': 'this marker is placed at',
        'enemies': 'it is shot by',
        'warpType': 'this is a',
            'timeWarp': 'timeWarp marker',
            'spinRate': 'spinRate marker',
        'val': 'his value is',
        'shotType': 'this bullet marker shots a',
            'bulletType': 'of',
        'aim': 'it is aimed toward the',
            'mid': 'middle',
            'pl': 'player',
        'offset0': 'its starting offset is',
        'offset1': 'its ending offset is',
        'amount': 'the bullet amount is',
        'amount0': 'its starting amount is',
        'amount1': 'its ending amount is',
        'angle0': 'its starting angle is',
        'angle1': 'its ending angle is',
        'speed0': 'its starting speed is',
        'speed1': 'its ending speed is',
        'rows': 'this wave\'s row count is',
        'lifespan': 'this homing tracks the player for',
        'duration': 'this stream\'s duration is'
    }
}
